### ISSUE TITLE
Implement perturbation space

### ISSUE THREAD

**Issue by Zethson** [theislab/pertpy#244]
### Description of feature

Instead of treating every dot in an embedding (visualization) as a cell, we want to summarize the whole perturbation as a dot.

Features that we need:
1. Generating perturbation spaces (see below)
2. Visualizing perturbation spaces (with scanpy's UMAP/T-SNE embeddings)
3. Enable arithmetic in the perturbation space 

There are a couple of options to get into this perturbation space:
1. Take the pseudobulk per perturbation (mean/median/sum)
2. Take the centroid of a cell embedding per perturbation
3. Mo's clustering
4. Mo's difference (more or less already done)
5. Mo's discriminator classifier
6. Mo's meta cell approaches
7. Train scVI and get the perturbation vectors, then mean/median/sum <- this is likely a bad idea since it would get rid of the perturbation effects
8. Train scVI and use the perturbations as batches/covariates. Add a discriminator in the latent space for the perturbations. Get the vectors and then mean/median/sum.
9. Try to use prior knowledge. First try to get all pathways with https://decoupler-py.readthedocs.io/en/latest/notebooks/progeny.html -> use them as an additional loss for the training of the 
10. Supervising with the pathways themselves? If we know which pathways are targeted, we could somehow infer distances between perturbations and use that in training. Maybe even pretrain a graph (similar to what scGLUE does) where nodes correspond to perturbations, and then use this graph in VAE training
11. Learn a mask on the input for each perturbation

We use some of pertpy's datasets. Let's start with RNA of https://pertpy.readthedocs.io/en/latest/usage/data/pertpy.data.papalexi_2021.html

**Comment by M0hammadL** [comment]
Hi @vfschumann  @Zethson, and thanks for starting this; here is how I think about it, we should try to stick with the most straightforward approaches possible:

- [ ]  Data summarization/sketching:


1.  try to use the mean of gene expression as a baseline and then apply a hierarchical or clustering method. In case of access to groupings for perturbations (for example, MoA for sciPlex3 or gene programs for Norman 2019 dataset we can maximize the clustering accuracy using NMI, ARI, ASW (see SCIB). We can repeat this approach using an embedding, for example, PCA or scGen/scVI.
2. Trying to approach one with one difference that for each mean gene expression, we subtract the mean of the control to obtain a differential response (for embedding approaches, we do the same thing, but in the embedding) 

3. Instead of reducing the only to mean, we leverage the pseudo-bulking approach (https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1812-2) or   (https://github.com/dpeerlab/SEACells) 
 and repeat the analysis.  This will allow us to still a bit of heterogeneity from single-cell data. 
 
 - [ ] Leveraging discriminator classifier: The idea here is that we fit either a regressor model for gene expression (see Supplemental Materials. here https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7289078/ (Dose-response analysis) and Sup 17-19) and we use either coefficient of the model for each perturbation as a feature or train a classifier example (simple MLP or logistic regression and take the penultimate layer as feature space and apply pseudo bulking approach above)


Metrics to assess all above: NMI, ARI, and ASW to evaluate all approaches above 

The best dataset to start from: is Nomran 2019, sciplex3, and also mixexcape original escape tutorial with groupings obtained from there.
