### ISSUE TITLE
pt.pl.milo.nhood_graph throws StopIteration error

### ISSUE THREAD

**Issue by Lilly-May** [theislab/pertpy#408]
### Report

Running the following code throws a StopIteration error in the last code line (when the plot is created):

```
adata = pt.dt.bhattacherjee()
milo = pt.tl.Milo()
mdata = milo.load(adata)
sc.pp.neighbors(mdata["rna"])
sc.tl.umap(mdata["rna"])
milo.make_nhoods(mdata["rna"])
mdata = milo.count_nhoods(mdata, sample_col="orig.ident")
milo.da_nhoods(mdata, design="~label")
milo.build_nhood_graph(mdata)
pt.pl.milo.nhood_graph(mdata)
```

Could someone please test if you can reproduce this error?

**Comment by Zethson** [comment]
I can test this soonish

**Comment by Zethson** [comment]
But @wxicu already has a setup - do you mind testing this as well, please?

**Comment by wxicu** [comment]
@Lilly-May Hi, I didnt have such error. Could you please try this again and check whether this error still exists? Happy to help further :)

**Comment by Lilly-May** [comment]
Thanks for testing!
I tested it on Google Colab, and unfortunately, it still doesn't work there. Everything else for Milo works on colab, so it's probably something specific about this plotting method? @wxicu, could you maybe test if you face the same issue when using Colab?

**Comment by wxicu** [comment]
Hey, two things I just figured out:

- The StopIteration error is caused by all NaN values of `nhood_adata.obs["graph_color"]`, which is used as the key for annotation by `sc.pl.embedding`.  When I try on colab, the version of matplotlib is 3.7.1, upgrading to 3.8.0 resolves this issue but will return a plot without any color annotation.

![image](https://github.com/theislab/pertpy/assets/102925032/452d1b03-a0fd-4d62-96ce-1a814e935ca4)

- The NaN values are indeed due to the reason that spatialFDR calculated in `milo.da_nhoods` is not significant, all >0.1.

**Comment by Zethson** [comment]
@wxicu thank you so much for digging into this. 
So you're saying that since nothing is significant in the data it's actually fine with the latest matplotlib version, right? Or is the calculation also off?

**Comment by wxicu** [comment]
> @wxicu thank you so much for digging into this. So you're saying that since nothing is significant in the data it's actually fine with the latest matplotlib version, right? Or is the calculation also off?

I dont think the calculation is off. Maybe it is also important to ask what @Lilly-May wants with such an analysis. I am not really familiar with the data. But since samples were collected a three time points in this dataset, with 3 levels in a category, it is better to specify the comparison we want to make in `model_contrast` by:
```
milo.da_nhoods(mdata, 
               design='~label', 
               model_contrasts='labelwithdraw_15d_Cocaine-labelwithdraw_48h_Cocaine')
```
![image](https://github.com/theislab/pertpy/assets/102925032/620fc5a6-7af7-4a9b-90cc-949dc15ac1ba)

**Comment by Lilly-May** [comment]
Hi @wxicu, thanks for looking into this! I'm not interested in the analysis per se; my goal was to add documentation examples for all methods, and then I noticed that this plotting method throws an error for that particular case. However, it seems that this is a specific problem when using matplotlib 3.7. So, I'll close this issue for now and add a docs example for `pt.pl.milo.nhood_graph` shortly.
Thank you so much for your help with this!😊
