### ISSUE TITLE
Improve tool explanations in docs

### ISSUE THREAD

**Issue by Lilly-May** [theislab/pertpy#474]
### Description of feature

In my opinion, the docs would benefit from an overview providing a brief explanation of what each tool does.
While some tools on the tutorials page have short descriptions, others lack them or give a technical explanation without biological context (e.g. _Milo - KNN based differential abundance analysis_). 

Maybe we could add a table or something similar above where we summarize each tool. Helpful could also be to "explain" each tool by providing questions one can answer using that tool. E.g. "How does the cell composition of my data change in response to a perturbation?" --> Milo

- [ ] Group Tutorials and have a small introduction for each group
- [ ] Improve Tutorial headings (e.g. for Milo (very technical heading) and Mixscape (heading doesn't say anything about what the tool actually does; _Perturbation assignment_ or _scoring_ would fit better))

**Comment by Zethson** [comment]
Thank you for raising this!

I'm not sure whether I like another table because we already grouped the tools into categories it feels like we'd be grouping them again somehow.

I think that having the tutorials better grouped with small introduction sections like we discussed will help a lot. I'd also improve the descriptions of the first cell in the tutorials and the usage documentation.

**Comment by Zethson** [comment]
I didn't add a table yet but I improved it at least. We might revisit this later but we have other priorities for now.
